# Generated by Django 3.0.7 on 2020-07-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcos_medication', models.CharField(max_length=1000)),
                ('other_medication', models.CharField(max_length=1000)),
                ('allergies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mensis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_age_first_period', models.CharField(blank=True, default='none', max_length=5, null=True)),
                ('m_date_last_period', models.DateField()),
                ('m_cycle_len', models.CharField(blank=True, default='none', max_length=5, null=True)),
                ('m_period_len', models.CharField(blank=True, default='none', max_length=5, null=True)),
                ('m_flow_amount', models.CharField(default='Medium', max_length=100)),
                ('m_pain_scale', models.CharField(default='Medium', max_length=100)),
                ('m_bleed', models.CharField(default='no', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=None)),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('height_feet', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('height_inches', models.CharField(blank=True, default=None, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pcos_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcos_diagnosed_age', models.CharField(default='less than 20', max_length=128)),
                ('acne', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('excess_hair_growth', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('irr_period', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('weight_gain', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('hair_loss', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('diff_conceiving', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('poly_cystic_ovaries', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('other', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('none', models.CharField(blank=True, default='not_correct', max_length=100, null=True)),
                ('lactation', models.CharField(blank=True, default='appropriate', max_length=100, null=True)),
                ('skin_tag_armpit', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('sleeping_disorder', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('hypothyroidism', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('sudden_hunger', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('headaches', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('sex_drive', models.CharField(blank=True, default='normal', max_length=100, null=True)),
                ('feel_of_guilt', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose_of_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('add_reason', models.CharField(max_length=1000)),
                ('docfile', models.FileField(default='none', upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('t_age', models.IntegerField()),
            ],
        ),
    ]
