# Generated by Django 2.2.2 on 2020-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200730_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcos_history',
            name='pcos_diagnosed_age',
            field=models.CharField(blank=True, default='less than 20', max_length=128, null=True),
        ),
    ]
